---
- src: https://github.com/stackhpc/ansible-role-openhpc
  version: jg-actions
  name: stackhpc.openhpc
- src: stackhpc.nfs
- src: https://github.com/stackhpc/ansible-role-ofed
  version: master
  name: stackhpc.ofed
